# Generated by Django 6.0.6 on 2026-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library_name",
                    models.CharField(default="City Central Library", max_length=255),
                ),
                ("library_code", models.CharField(default="CCL-2026", max_length=50)),
                ("language", models.CharField(default="English", max_length=50)),
                (
                    "timezone",
                    models.CharField(
                        default="(GMT+05:45) Asia/Kathmandu", max_length=100
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD MMM YYYY (e.g. 27 May 2026)", max_length=50
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="NPR - Nepali Rupee (Rs)", max_length=50),
                ),
                ("address", models.TextField(default="123 Library Street, Kathmandu")),
                ("phone", models.CharField(default="+977 9800000000", max_length=20)),
                (
                    "email",
                    models.EmailField(default="library@uni.edu.np", max_length=254),
                ),
                ("website", models.URLField(default="https://library.uni.edu.np")),
                ("established", models.CharField(default="2010", max_length=4)),
                ("total_floors", models.CharField(default="3", max_length=10)),
                ("email_on_issue", models.BooleanField(default=True)),
                ("email_on_return", models.BooleanField(default=True)),
                ("email_on_overdue", models.BooleanField(default=True)),
                ("sms_on_overdue", models.BooleanField(default=False)),
                ("reminder_days_before", models.CharField(default="2", max_length=10)),
                (
                    "overdue_alert_frequency",
                    models.CharField(default="Daily", max_length=50),
                ),
                ("auto_backup", models.BooleanField(default=True)),
                ("backup_frequency", models.CharField(default="Weekly", max_length=50)),
                (
                    "last_backup",
                    models.CharField(default="27 May 2026, 02:30 PM", max_length=100),
                ),
                (
                    "backup_location",
                    models.CharField(default="Cloud Storage", max_length=100),
                ),
            ],
        ),
    ]
