# Generated by Django 6.0.6 on 2026-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0002_issuebook_fine_status_fine_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuebook",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
