# Generated by Django 6.0.6 on 2026-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0003_issuebook_last_reminder_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="request_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
