# Generated by Django 6.0.6 on 2026-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image_file",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
