# Generated by Django 6.0.6 on 2026-07-24 19:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_elibraryresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibraryresource',
            name='resource_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='elibrary/'),
        ),
    ]
