# Generated by Django 6.0.6 on 2026-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_elibraryresource_resource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elibraryresource',
            name='resource_file',
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='file_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=100),
        ),
    ]
