# Generated by Django 6.0.6 on 2026-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_elibraryresource_resource_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
